
volumes:
  static:
  media:
  neo4j_data:


services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.neo4j
    container_name: ${COMPOSE_PROJECT_NAME}-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7474"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=task_track.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend/
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    ports:
      - "127.0.0.1:9000:80"
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media