GET http://localhost:8000/api/group/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NDYwOTYzNjgsImlhdCI6MTc0NjA1MzE2OCwidG9rZW5fdHlwZSI6ImFjY2VzcyJ9.cSVykydcb0UCj1p22YbXTs7kknj9UBc7MEW3SP_O9mA
Content-Type: application/json

{}

###

POST http://localhost:8000/api/group/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NDYwOTYzNjgsImlhdCI6MTc0NjA1MzE2OCwidG9rZW5fdHlwZSI6ImFjY2VzcyJ9.cSVykydcb0UCj1p22YbXTs7kknj9UBc7MEW3SP_O9mA
Content-Type: application/json

{
    "name": "Разработка"
}
