GET http://localhost:8000/api/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTQxNDk1LCJqdGkiOiJiZWY1ZTZjODJhYWE0NTVkOTU3MzVlMjVmYzJjNWY2YSIsInVzZXJfaWQiOi05ODEzMDU1ODA4NDk1NjM0ODIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSJ9.Hemfvty381iKfezLdPR7K9zFQ7XA4RSy6BS6Du2-DxU
Content-Type: application/json

{}


###

POST http://localhost:8000/api/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTQxNDk1LCJqdGkiOiJiZWY1ZTZjODJhYWE0NTVkOTU3MzVlMjVmYzJjNWY2YSIsInVzZXJfaWQiOi05ODEzMDU1ODA4NDk1NjM0ODIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSJ9.Hemfvty381iKfezLdPR7K9zFQ7XA4RSy6BS6Du2-DxU
Content-Type: application/json

{
    "name": "Попашка"
}
