GET http://localhost:8000/api/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2hhaWxAZXhhbXBsZS5jb20iLCJleHAiOjE3NDU5NjkzNjcsImlhdCI6MTc0NTk2NTc2NywidG9rZW5fdHlwZSI6ImFjY2VzcyJ9.0ttaI3FfqynMGxEiY1VpYyj88aOFvx0QqO2n78T1oHA
Content-Type: application/json

{}


###

POST http://localhost:8000/api/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2hhaWxAZXhhbXBsZS5jb20iLCJleHAiOjE3NDU5NjkzNjcsImlhdCI6MTc0NTk2NTc2NywidG9rZW5fdHlwZSI6ImFjY2VzcyJ9.0ttaI3FfqynMGxEiY1VpYyj88aOFvx0QqO2n78T1oHA
Content-Type: application/json

{
    "name": "Шомашка"
}

###

PUT http://localhost:8000/api/group/шомашка/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2hhaWxAZXhhbXBsZS5jb20iLCJleHAiOjE3NDU5NjkzNjcsImlhdCI6MTc0NTk2NTc2NywidG9rZW5fdHlwZSI6ImFjY2VzcyJ9.0ttaI3FfqynMGxEiY1VpYyj88aOFvx0QqO2n78T1oHA
Content-Type: application/json

{
    "name": "Шомка"
}
