GET http://localhost:8000/api/task/?page_size=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NDYyMjk1MTUsImlhdCI6MTc0NjE4NjMxNSwidG9rZW5fdHlwZSI6ImFjY2VzcyJ9.kacNSC1Vj_KQqIaHwjTGLRVC1JsNAH_DBr_dvHy5Qa4
Content-Type: application/json

{}