FROM neo4j:5-community

ENV NEO4J_AUTH=neo4j/test
ENV NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
ENV NEO4J_apoc_import_file_enabled=true
ENV NEO4J_dbms_security_allow__csv__import__from__file__urls=true
ENV NEO4J_apoc_initialization_file=/var/lib/neo4j/import/init-trigger.cypher
